plugins {
    id "com.android.application"
}

android {
    namespace "com.example.yolocoffee"
    compileSdk 35

    defaultConfig {
        applicationId "com.example.yolocoffee"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "1.0"
    }

    androidResources {
        noCompress "onnx"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation "com.microsoft.onnxruntime:onnxruntime-android:1.24.3"
    implementation "androidx.core:core:1.13.1"
}

